### ISSUE TITLE
As a NOI visitor I want to have maps.noi.bz.it online in order to find the room that I'm looking for

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.noi.maps#1]
The steps are:
- [x] ask to MadeInCima to upload the source code and the documentation in the repository @sseppi 
- [x] create the pipeline

**Comment by sseppi** [comment]
The link to the stage version is:
http://stage.madeincima.it/noi-maps/

**Comment by bertolla** [comment]
When will the code be uploaded?

**Comment by bertolla** [comment]
The Readme.md is completly wrong it talks about a JAVA project but it's written in php. I need a documentation on how to setup this app and how to run tests etc...
@sseppi Can you provide that thx

**Comment by bertolla** [comment]
@ohnewein @sseppi 
Please test this, so we can go in production ASAP.
https://maps.noi.testingmachine.eu/

**Comment by sseppi** [comment]
I've made some testing and all functionalities seems to be everything fine so I think we can go online. @bertolla

**Comment by ohnewein** [comment]
@bertolla as agreed we go live with this first MVP.

Thanks
