### ISSUE TITLE
As a content manager I want that odh understands my Spreadsheet, when it's just containing metadata like labels in different languages, so that maps.noi.bz.it can be completely moved to odh

### ISSUE THREAD

**Issue by bertolla** [noi-techpark/it.bz.noi.maps#16]

**Comment by bertolla** [comment]
Metadata like labels of things in NOI can now also be imported through the spreadsheets.
All you need to do is marking your id column with metadata-id and all columns will automatically be imported as metadata of a type. The type is uniqly identified through sheet and spreadsheet id.
You can see all labels through this query:
`http://tomcat.testingmachine.eu/v2/api/flat/NOI-Place/*?limit=200&offset=0&select=tmetadata%2Cmvalue&shownull=false&distinct=true`
(Currently there is not much data in the sheets)

The buildings sheet now is also available by simply adding the 3 identifiers `Beacon ID, Longitude, Latitude`.
And can be found in the overall list of places `http://tomcat.testingmachine.eu/v2/api/flat/NOI-Place/?limit=200&offset=0&shownull=false&distinct=true`

**Comment by ohnewein** [comment]
Hi @bertolla I do not understand how I could test this. The links in your description work. Is that enough as a test?

**Comment by bertolla** [comment]
You can test it by changing the spreadsheet(https://docs.google.com/spreadsheets/d/1SSXusoMlNpQd-_CtKjft2Zh2yaWhoqNes4GzZl_X0GI/edit#gid=1959162704) and see if 
 your changes are reflected on the data found on the api. Consider that it won't be instantly so it make take a minute or two before you changes will be shown.

**Comment by ohnewein** [comment]
Seams to work
