### ISSUE TITLE
As a maps.noi.bz.it manager I want to have the web component online in order to be able to publish it on different websites.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.noi.maps#18]

**Comment by bertolla** [comment]
Test environment MadeInCima: http://stage.madeincima.it/webcomponent/?shared=A1-1-33-L&lang=it

**Comment by bertolla** [comment]
Code is running on our test server now:https://maps.noi.testingmachine.eu/
I had to change link of webcomponent to our store site.
