### ISSUE TITLE
Armin R. wants to use Office 365 to change content in maps.noi.bz.it

### ISSUE THREAD

**Issue by ohnewein** [noi-techpark/it.bz.noi.maps#24]
- [x] test Office 365 integration with maps.noi.bz.it on testingmachine.eu
- [x] activate it on production and inform Armin, Ivan and Lukas, that from now on data has to be edited in Office365

**Comment by bertolla** [comment]
@sseppi me and Peter did all the changes to have https://maps.noi.testingmachine.eu/ pointing at the data on testingmachine odh.
If you change things in the office spreadsheet it should be reflected on the website itself.
Please test it so I will put it on production ASAP.
Cheers,
Patrick

**Comment by sseppi** [comment]
@bertolla i've tried to make some changes in the following Excel
[https://noibz.sharepoint.com/:x:/s/UNITshrdTech-TransferDigital/EUHPEo4RKAlFrTFfi5PP6G4BZblg-ZmuO7yNIaG6pxprvw?e=uYw7kT](https://noibz.sharepoint.com/:x:/s/UNITshrdTech-TransferDigital/EUHPEo4RKAlFrTFfi5PP6G4BZblg-ZmuO7yNIaG6pxprvw?e=uYw7kT)

It seems that the changes doesn't go to [https://maps.noi.testingmachine.eu/](https://maps.noi.testingmachine.eu/), is it the right spreadsheet that I changed?

**Comment by sseppi** [comment]
I've tested trying to change something in the Office 365 Excel and it worked.

@bertolla will you do a copy of the actual content of the Google Spreadsheet in the Excel file before to go on production?

**Comment by bertolla** [comment]
Is there a reason why I should? We are only reading, never writing.
You will need to reschedule the going live, I'm on vacation from tomorrow on and I don't wanna deploy to production and not be here, if something is not working.

**Comment by sseppi** [comment]
Regarding the spreadsheet, while we were developing the collector Lukas Nagler changed some contents. So we need to align the two spreadsheets before to go live. I've asked if you can do since you did the last time the same.

I agree. We can schedule the go live after you will come back from vacation.

**Comment by bertolla** [comment]
No, i didn't do that last time. I never copied the contents from one to another. I don't know the differences between the spreadsheets. You will need to sync both once, before we go live!
You'll need to lock the google one and than sync everything to office365.

**Comment by bertolla** [comment]
@sseppi Ho do we proceed, should we set a date for the migration? Have you locked and synced the google spreadsheet?

**Comment by sseppi** [comment]
@bertolla I've copied the content from the Google Spreadsheet to the Office 365 one so we should be ready to make the switch-off.

Tell me when you are able to make the swhitch so I can then send an email to Lukas, Armin and Fabian with the link to the new Excel.

**Comment by bertolla** [comment]
@sseppi 
Ok, you better lock the google spreadsheet to avoid issues afterwards.
Have you checked if https://maps.noi.testingmachine.eu/ is still working as intended?
I will try to do the changes this afternoon or tomorrow in the morning
