### ISSUE TITLE
Create a parameter to hide the title, menu, footer and cookie banner

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.noi.maps#27]
Used inside the NOI Community App

**Comment by RudiThoeni** [comment]
I think this request should be done to madeincima by the PM who manages maps.noi.bz?

**Comment by Piiit** [comment]
@sseppi @RudiThoeni Did someone already inform the developers?

**Comment by sseppi** [comment]
@Piiit I will send them an email.

Just a question, couldn't Dimension simply use the web component? Do we have the same problem also with it?

**Comment by Piiit** [comment]
Done in https://github.com/noi-techpark/it.bz.noi.maps/pull/30 and https://github.com/noi-techpark/webcomp-maps-noi/pull/17
